apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: docker.io/dbgurum/argoupdater:nginx21a
        name: sample
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
