apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: dbgurum/argoupdater:nginx19a
        name: myweb
        ports:
        - containerPort: 80
